### ISSUE TITLE
Syntax error when I Run Wandalen/wretry.action@v1.0.36_js_action

### ISSUE THREAD

**Issue by Psalmz777** [Wandalen/wretry.action#125]
I Keep getting this in my github workflow but I have been using this action for a while now
 Run Wandalen/wretry.action@v1.0.36
Run Wandalen/wretry.action@v1.0.36_js_action
/home/runner/work/_actions/Wandalen/yaml-update-action/dist/index.js:25766
      const responseObject = new Response(response.body?.source ?? null)
                                                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/Wandalen/wretry.action/v1.0.36_js_action/src/Runner.js:21:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
/home/runner/work/_actions/Wandalen/yaml-update-action/dist/index.js:25[766](https://github.com/airqo-platform/AirQo-frontend/actions/runs/7018585492/job/19094300600#step:11:768)
      const responseObject = new Response(response.body?.source ?? null)
                                                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/Wandalen/wretry.action/v1.0.36_js_action/src/Runner.js:21:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Error: Process returned exit code 1
Launched as "node /home/runner/work/_actions/Wandalen/wretry.action/v1.0.36_js_action/src/Runner.js /home/runner/work/_actions/Wandalen/yaml-update-action/dist/index.js"

**Comment by dmvict** [comment]
Hello @Psalmz777 

It's strange for me. 

I have two questions. 
Did you try new version of the action? 
Can you share a workflow part where the action is used?

**Comment by Psalmz777** [comment]
Hello @dmvict 

I have not tried a newer version of the action yet ,lemme give it a try and I let you know 
Also here is the part of the workflow where it is used 

      - name: Update corresponding helm values file(with retry)
        uses: Wandalen/wretry.action@v1.0.36 # Retries action on fail
        with:
          action: fjogeleit/yaml-update-action@main # Action to retry
          with: |
            valueFile: "k8s/netmanager/values-stage.yaml"
            propertyPath: "image.tag"
            value: ${{ needs.image-tag.outputs.build_id }}
            branch: ${{ env.DEPLOY_BRANCH }}
            token: ${{ secrets.YAML_UPDATER_TOKEN }}
            message: "Update netmanger staging image tag to ${{ needs.image-tag.outputs.build_id }}"
            createPR: false

**Comment by dmvict** [comment]
Hello @Psalmz777 

Can you try the new version of the action and give me a feedback?
