### ISSUE TITLE
Getting this error just using it.

### ISSUE THREAD

**Issue by jhamestoy** [Wandalen/wretry.action#36]
Using it in this way with an http-request actions that was previously working fine : 

![image](https://user-images.githubusercontent.com/94137431/145416347-a347d63f-ac31-44e4-89c5-e7c250c7db1d.png)

**getting this error :**
====================================================================================
Post job cleanup.
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/ec2-user/actions-runner/_work/_actions/Wandalen/wretry.action/v1.0.11/src/Post.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ec2-user/actions-runner/_work/_actions/Wandalen/wretry.action/v1.0.11/src/Post.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ec2-user/actions-runner/_work/_actions/Wandalen/wretry.action/v1.0.11/src/Post.js'
  ]
}
======================================================================================

**Comment by jhamestoy** [comment]
why this is not packaged to be used? im missing something?

**Comment by dmvict** [comment]
> why this is not packaged to be used? im missing something?

Hello, @jhamestoy . 

We implemented this action to retry another actions. For this we need to implement many features of Github Actions API. One of the features is resolving variables. So, the example above cannot work now. 

Now action accepts only hardcoded values. 

=== 

Maybe, your problem has different reasons. 
Can you reproduce problem in some minimal working example with hardcoded options?

I wrote test routine in experimental branch and [received another fail](https://github.com/dmvict/wretry.action/runs/4480487403?check_suite_focus=true#step:11:1477).

**Comment by Wandalen** [comment]
@jhamestoy is problem still happen?

**Comment by jhamestoy** [comment]
> @jhamestoy does the problem still happen?

Ive used a differnt solution, instead actions, just a bash script. Thanks for ask!
